name: compile LaTeX when PR update

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  PRbuild:
    name: PRBuild
    runs-on: self-hosted
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: compile latex document
        uses: ./.github/actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: comment pdf to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_URL: ${{ github.event.pull_request.head.repo.clone_url }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
          URL: ${{ github.event.pull_request.html_url }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "latex-template@minervajuppiter.net"
          gh repo clone $GIT_URL
          cd ${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}
          git fetch origin $BRANCH
          git checkout $BRANCH
          cp ../main.pdf ./converted/
          git add .
          git commit -m "add pdf to PR"
          git push