name: compile LaTeX when PR update

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  PRbuild:
    name: PRBuild
    runs-on: self-hosted
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: compile latex document
        uses: ./.github/actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: main
          path: ./main.pdf
      - name: Add comment to PR
        uses: unsplash/comment-on-pr@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          body: |
            The PDF has been generated successfully. You can download it [here](${{ artifact_url }}).
            Please check the build log for any errors or warnings.