name: compile LaTeX when PR update

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  PRbuild:
    name: PRBuild
    runs-on: self-hosted
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: compile latex document
        uses: ./.github/actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: comment pdf to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_URL: ${{ github.event.pull_request.head.repo.clone_url }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
          URL: ${{ github.event.pull_request.html_url }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          gh repo clone $GIT_URL
          cd ${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}
          git fetch origin $BRANCH
          git checkout $BRANCH
          cp ../main.pdf ./converted/
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "add pdf to PR"
          git remote set-url origin https://<username>:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push