name: compile LaTeX when PR update

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  PRbuild:
    name: PRBuild
    runs-on: self-hosted
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: compile latex document
        uses: ./.github/actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TEX_FILE }}
          path: ./main.pdf