name: compile LaTeX when PR update

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  PRbuild:
    name: PRBuild
    runs-on: self-hosted
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: compile latex document
        uses: ./.github/actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: comment pdf to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_URL: ${{ github.event.pull_request.head.repo.clone_url }}
          REPO_NAME: ${{ github.repository.name }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
          URL: ${{ github.event.pull_request.html_url }}
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "example@example.com"
          git clone $GIT_URL
          cd $REPO_NAME
          git checkout $BRANCH
          cp ../main.pdf ./converted/
          git add .
          git commit -m "add pdf to PR"
          git push