name: compile LaTeX when PR update

on:
  push:
    branches-ignore:
      - NotBuild


jobs:
  PRbuild:
    name: PushBuild
    runs-on: self-hosted
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: compile latex document
        run: |
          latexmk -pdfdvi main.tex
      - name: Upload PDF artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: main
          path: ./main.pdf
          retention-days: 7